### ISSUE TITLE
i starting too high

### ISSUE THREAD

**Issue by Tishj** [hilmi-yilmaz/malloc_failer#2]
```c
static void	*xmalloc(size_t size)
{
	static int fail = 0;
	static int i = 1;

	if (i == fail)
		return (NULL);
	i++;
	return (malloc(size));
}
```
I set the `at_which_malloc_to_fail` to 0, because i starts at 1 this will never happen
also if I could make a suggestion, there's no need for 2 static variables, since one is generated anyways, `if (i == X)` would be enough I think :P?

**Comment by hilmi-yilmaz** [comment]
Fixed the at_which_malloc_to_fail. Now the user can only enter values starting from 1. Also removed the static from fail varibale. Thanks Thijs!
